# Generated by Django 5.1.7 on 2025-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedb',
            name='description2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
