# Generated by Django 5.1.7 on 2025-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(blank=True, max_length=100, null=True)),
                ('Cnumber', models.IntegerField(blank=True, null=True)),
                ('Cemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Cmessage', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
